name: Model Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: ['.NET', 'PHP', 'Ruby', 'TypeScript']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: models-lib
    
    - name: Use Node.js 18.17.1
      uses: actions/setup-node@v1
      with:
        node-version: 18.17.1
  
    - run: npm install
      working-directory: models-lib
  
    - name: Update models-lib with latest data-models
      run: npm update @openactive/data-models
      working-directory: models-lib
  
    - name: Generate ${{ matrix.language }} models
      run: npm start -- generate ${{ matrix.language }} --destination ../output/
      working-directory: models-lib

